### ISSUE TITLE
Does it work with fs 2.4?

### ISSUE THREAD

**Issue by tkossak** [media-proxy/fs.youtube#15]
[setup.cfg](https://github.com/media-proxy/fs.youtube/blob/master/setup.cfg#L37) still has requirement `fs==2.3.0` so my poetry complains when installing `fs.youtube` with latest `fs` (2.4.4):
```
Because no versions of fs.youtube match >0.2.5,<0.3.0
 and fs.youtube (0.2.5) depends on fs (2.3.0), fs.youtube (>=0.2.5,<0.3.0) requires fs (2.3.0).
So, because test_package depends on both fs (^2.4) and fs.youtube (^0.2.5), version solving f
ailed.
```

**Comment by media-proxy** [comment]
@tkossak 
Updated now:

fs==2.4.4
pafy==0.5.4
youtube-dl==2019.3.1

+ Pipy update.
Please test

**Comment by tkossak** [comment]
Works, thank you.
